/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "im_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace im {


AccessMessage::~AccessMessage() throw() {
}


void AccessMessage::__set_uid(const int32_t val) {
  this->uid = val;
}

void AccessMessage::__set_beam_id(const std::vector<int32_t> & val) {
  this->beam_id = val;
}

void AccessMessage::__set_content(const std::string& val) {
  this->content = val;
}

uint32_t AccessMessage::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->uid);
          this->__isset.uid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->beam_id.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->beam_id.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += iprot->readI32(this->beam_id[_i4]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.beam_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->content);
          this->__isset.content = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t AccessMessage::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("AccessMessage");

  xfer += oprot->writeFieldBegin("uid", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->uid);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("beam_id", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->beam_id.size()));
    std::vector<int32_t> ::const_iterator _iter5;
    for (_iter5 = this->beam_id.begin(); _iter5 != this->beam_id.end(); ++_iter5)
    {
      xfer += oprot->writeI32((*_iter5));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("content", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->content);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(AccessMessage &a, AccessMessage &b) {
  using ::std::swap;
  swap(a.uid, b.uid);
  swap(a.beam_id, b.beam_id);
  swap(a.content, b.content);
  swap(a.__isset, b.__isset);
}

AccessMessage::AccessMessage(const AccessMessage& other6) {
  uid = other6.uid;
  beam_id = other6.beam_id;
  content = other6.content;
  __isset = other6.__isset;
}
AccessMessage& AccessMessage::operator=(const AccessMessage& other7) {
  uid = other7.uid;
  beam_id = other7.beam_id;
  content = other7.content;
  __isset = other7.__isset;
  return *this;
}
void AccessMessage::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "AccessMessage(";
  out << "uid=" << to_string(uid);
  out << ", " << "beam_id=" << to_string(beam_id);
  out << ", " << "content=" << to_string(content);
  out << ")";
}

} // namespace
