// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "LogicInterface.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::im;

class LogicInterfaceHandler : virtual public LogicInterfaceIf {
 public:
  LogicInterfaceHandler() {
    // Your initialization goes here
  }

  void AccessToLogic(const std::string& request) {
    // Your implementation goes here
    printf("AccessToLogic\n");
  }

  void LogicToAccess(const AccessMessage& response) {
    // Your implementation goes here
    printf("LogicToAccess\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<LogicInterfaceHandler> handler(new LogicInterfaceHandler());
  shared_ptr<TProcessor> processor(new LogicInterfaceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

